/**
 * Renders src/data/quran-quotes.json as docs/ayah-review.md — the document a
 * human (imam) reads to approve, reject or replace entries.
 *
 * The reviewer sees the exact text the bot will post, with the citation, so the
 * approval is of real output rather than of a reference list.
 *
 * Run:  npx tsx scripts/export-quotes-review.ts
 */
import fs from "node:fs";
import path from "node:path";

const root = path.resolve(__dirname, "..");
const quotesPath = path.join(root, "src/data/quran-quotes.json");
const outPath = path.join(root, "docs/ayah-review.md");

interface Quote {
  reference: string;
  surah: number;
  ayah: number;
  surahNameEnglish: string;
  theme: string;
  bn: string;
  en: string;
}

function main(): void {
  const file = JSON.parse(fs.readFileSync(quotesPath, "utf8"));
  const quotes: Quote[] = file.quotes;

  const byTheme = new Map<string, Quote[]>();
  for (const q of quotes) {
    if (!byTheme.has(q.theme)) byTheme.set(q.theme, []);
    byTheme.get(q.theme)!.push(q);
  }

  const md: string[] = [
    "# Ayah review",
    "",
    `${quotes.length} ayahs, pending approval. Generated by ` +
      "`npx tsx scripts/export-quotes-review.ts` — do not edit this file; it is overwritten.",
    "",
    "## How to review",
    "",
    "For each entry, mark one of:",
    "",
    "- **keep** — fine to post as-is",
    "- **remove** — should not be posted (unsuitable quoted alone, or a poor fit)",
    "- **replace with X:Y** — swap for a different ayah",
    "",
    "The question for each is narrower than *is this ayah good* — it is: **does this",
    "read correctly as a standalone message, with no surrounding context, sent to a",
    "workplace Discord channel at prayer time?** An ayah can be perfectly sound and",
    "still be a poor fit alone.",
    "",
    "Send back the marked list. Edits go into `scripts/quran-refs.json` (references",
    "only), then the file is regenerated and re-verified — the text below is never",
    "hand-edited.",
    "",
    "## Sources",
    "",
    `- Text fetched from **${file.source}**`,
    `- Bangla: **${file.editions.bn.translator}** (${file.editions.bn.translatorEnglish}), edition \`${file.editions.bn.identifier}\``,
    `- English: **${file.editions.en.translator}**, edition \`${file.editions.en.identifier}\``,
    `- Generated ${file.generatedAt}`,
    "",
    "Every ayah below was cross-checked against an independent distributor of the",
    "same translation — see `ayah-crosscheck.md`.",
    "",
    "## How it will appear in Discord",
    "",
    "```",
    "@everyone",
    "Asr Prayer time - 04:15 PM",
    "<the waqt's configured message>",
    "```",
    "",
    "…followed by an embed containing the Bangla text, a divider, the English text,",
    "and the citation in small print at the bottom.",
    "",
    "---",
    "",
  ];

  let n = 0;
  for (const [theme, group] of byTheme) {
    md.push(`## ${theme} (${group.length})`, "");
    for (const q of group) {
      n++;
      md.push(
        `### ${n}. ${q.reference} — Surah ${q.surahNameEnglish}`,
        "",
        `> ${q.bn}`,
        ">",
        `> ${q.en}`,
        "",
        "`keep` / `remove` / `replace with ___`",
        "",
      );
    }
  }

  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, md.join("\n"), "utf8");
  console.log(`Wrote ${quotes.length} entries -> ${path.relative(root, outPath)}`);
}

main();
